#!/usr/bin/env python3
"""Generate portable LLM documentation from the canonical Markdown docs."""

import argparse
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
RAW_BASE = "https://raw.githubusercontent.com/faustbrian/go-wire/main"


def documentation_paths(readme: str) -> list[pathlib.Path]:
    match = re.search(
        r"^## Documentation\s*$\n(?P<body>.*?)(?=^## |\Z)",
        readme,
        flags=re.MULTILINE | re.DOTALL,
    )
    if match is None:
        raise ValueError("README.md does not contain a Documentation section")

    paths = []
    for target in re.findall(
        r"^- \[[^]]+\]\(([^)]+\.md)\)\s*$", match["body"], re.MULTILINE
    ):
        path = ROOT / target
        if not path.is_file():
            raise ValueError(f"README.md references missing documentation: {target}")
        paths.append(path)
    if not paths:
        raise ValueError("README.md Documentation section has no Markdown documents")
    return paths


def title(document: str, path: pathlib.Path) -> str:
    match = re.search(r"^# (.+)$", document, flags=re.MULTILINE)
    if match is None:
        raise ValueError(f"{path.relative_to(ROOT)} has no level-one heading")
    return match.group(1)


def summary(document: str) -> str:
    lines = document.splitlines()
    paragraph = []
    after_title = False
    in_code = False
    for line in lines:
        if not after_title:
            after_title = line.startswith("# ")
            continue
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if not line.strip():
            if paragraph:
                break
            continue
        if line.startswith(("#", "- ")):
            if paragraph:
                break
            continue
        paragraph.append(line.strip())
    return " ".join(paragraph)


def render_index(readme: str, paths: list[pathlib.Path]) -> str:
    lines = [
        f"# {title(readme, README)}",
        "",
        f"> {summary(readme)}",
        "",
        "This index is generated from the repository's canonical Markdown documentation.",
        "",
        "## Documentation",
        "",
    ]
    for path in paths:
        document = path.read_text()
        relative = path.relative_to(ROOT).as_posix()
        lines.append(
            f"- [{title(document, path)}]({RAW_BASE}/{relative}): {summary(document)}"
        )
    lines.extend(
        [
            "",
            "## Complete documentation",
            "",
            f"- [llms-full.txt]({RAW_BASE}/llms-full.txt): All linked documentation in one file.",
            "",
        ]
    )
    return "\n".join(lines)


def render_full(readme: str, paths: list[pathlib.Path]) -> str:
    sections = [readme.rstrip()]
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        sections.extend([f"<!-- Source: {relative} -->", path.read_text().rstrip()])
    notice = "<!-- Code generated by scripts/generate-llms.py; DO NOT EDIT. -->"
    return notice + "\n\n" + "\n\n---\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    readme = README.read_text()
    paths = documentation_paths(readme)
    generated = {
        ROOT / "llms.txt": render_index(readme, paths),
        ROOT / "llms-full.txt": render_full(readme, paths),
    }

    stale = []
    for path, contents in generated.items():
        if args.check:
            if not path.is_file() or path.read_text() != contents:
                stale.append(path.name)
        else:
            path.write_text(contents)

    if stale:
        print("generated LLM documentation is stale: " + ", ".join(stale), file=sys.stderr)
        print("run scripts/generate-llms.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
